#!/usr/bin/env python3
"""Regenerate the three archive indices from each entry's metadata.json.

The indices were previously produced by a `scripts/advisory_index.sh` that was
never committed, so they could not be rebuilt and drifted out of step with the
entries. This replaces it:

  README.md          - the "Vulnerabilities by Product" listing, spliced between
                       the <!-- INDEX:START --> / <!-- INDEX:END --> markers so
                       the hand-written prose around it is untouched
  INDEX_BY_CLASS.md  - grouped by vulnerability class
  INDEX_BY_CWE.md    - grouped by weakness, entries without a CWE under Unmapped

    python3 tools/gen_indices.py            # rewrite all three
    python3 tools/gen_indices.py --check    # exit 1 if any is out of date
"""

import argparse
import json
import os
import sys
import urllib.parse

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from cwe_names import CWE_NAMES  # noqa: E402

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
START_MARKER = "<!-- INDEX:START -->"
END_MARKER = "<!-- INDEX:END -->"

PREAMBLE = (
    "*Generated by `tools/gen_indices.py` from the `metadata.json` of each entry. "
    "Do not edit by hand.*\n"
    "\n"
    "Every entry is a verified, reproduced exploit for a PUBLIC advisory, filed under its product. "
    "The id may\n"
    "come from any public namespace (CVE, GHSA, distro, vendor); when an advisory carries several ids "
    "it is\n"
    "filed under its CVE and the rest are listed as aliases.\n"
)


def link(path):
    """Repo-relative markdown link target for an entry directory."""
    return "./" + urllib.parse.quote(path.replace(os.sep, "/"))


def load_entries():
    """Every entry in the archive, annotated with its directory and product."""
    entries = []
    for dirpath, dirnames, filenames in os.walk(REPO_ROOT):
        dirnames[:] = [d for d in dirnames if not d.startswith(".") and d != "tools"]
        if "metadata.json" not in filenames:
            continue
        with open(os.path.join(dirpath, "metadata.json"), encoding="utf-8") as handle:
            entry = json.load(handle)
        relative = os.path.relpath(dirpath, REPO_ROOT)
        entry["_dir"] = relative
        entry["_product"] = entry.get("product") or relative.split(os.sep)[0]
        # Entries that predate the <Product>/<CLASS> - <ID> layout sit at the
        # repository root and stay there: renaming breaks inbound links.
        entry["_flat"] = os.sep not in relative
        entries.append(entry)
    return entries


def by_product_key(entry):
    return (entry["_product"].lower(), entry.get("class") or "", entry.get("id") or "")


def cwe_sort_key(cwe):
    """Numeric order, so CWE-89 precedes CWE-120."""
    try:
        return int(cwe.split("-", 1)[1])
    except (IndexError, ValueError):
        return 10**9


def render_product_index(entries):
    """The listing spliced into README.md, alphabetical by product."""
    lines = [START_MARKER, ""]
    products = {}
    for entry in entries:
        products.setdefault(entry["_product"], []).append(entry)

    for product in sorted(products, key=str.lower):
        lines.append(f"### {product}")
        for entry in sorted(products[product], key=by_product_key):
            label = f"{entry.get('class') or 'entry'} - {entry.get('id') or entry['_dir']}"
            lines.append(f"- [{label}]({link(entry['_dir'])})")
        lines.append("")

    flat = sorted((e for e in entries if e["_flat"]), key=by_product_key)
    if flat:
        lines.append(
            "> The following entries predate the `<Product>/<CLASS> - <ID>` layout and are kept at "
            "their original paths on purpose, since renaming them would break inbound links: "
            + ", ".join(f"[`{e['_dir']}`]({link(e['_dir'])})" for e in flat)
            + "."
        )
        lines.append("")

    lines.append(END_MARKER)
    return "\n".join(lines)


def render_class_index(entries):
    classes = {}
    for entry in entries:
        classes.setdefault(entry.get("class") or "Unclassified", []).append(entry)

    total = len(entries)
    lines = [
        "# Vulnerabilities by Class",
        "",
        PREAMBLE,
        f"{total} entries across {len(classes)} classes.",
        "",
    ]
    for name in sorted(classes):
        group = sorted(classes[name], key=by_product_key)
        lines.append("")
        lines.append(f"## {name} ({len(group)})")
        lines.append("")
        for entry in group:
            label = f"{entry['_product']} - {entry.get('id') or entry['_dir']}"
            fixed = (entry.get("fixed") or "").strip()
            suffix = f" - fixed in {fixed}" if fixed else ""
            lines.append(f"- [{label}]({link(entry['_dir'])}){suffix}")
    lines.append("")
    return "\n".join(lines)


def render_cwe_index(entries):
    weaknesses = {}
    unmapped = []
    for entry in entries:
        cwes = [c for c in (entry.get("cwe") or []) if c]
        if not cwes:
            unmapped.append(entry)
            continue
        for cwe in cwes:
            weaknesses.setdefault(cwe, []).append(entry)

    mapped = len(entries) - len(unmapped)
    lines = [
        "# Weaknesses by CWE",
        "",
        PREAMBLE,
        f"{mapped} of {len(entries)} entries carry a CWE mapping across "
        f"{len(weaknesses)} distinct weaknesses.",
        "",
    ]

    def bullet(entry):
        parts = [entry["_product"], entry.get("class") or "entry", entry.get("id") or entry["_dir"]]
        label = " - ".join(parts)
        severity = (entry.get("severity") or "").upper()
        if severity and severity != "UNKNOWN":
            label += f" ({severity})"
        return f"- [{label}]({link(entry['_dir'])})"

    for cwe in sorted(weaknesses, key=cwe_sort_key):
        name = CWE_NAMES.get(cwe)
        lines.append("")
        lines.append(f"## {cwe} - {name}" if name else f"## {cwe}")
        lines.append("")
        for entry in sorted(weaknesses[cwe], key=by_product_key):
            lines.append(bullet(entry))

    if unmapped:
        lines.append("")
        lines.append(f"## Unmapped ({len(unmapped)})")
        lines.append("")
        lines.append("No CWE is recorded upstream for these entries.")
        lines.append("")
        for entry in sorted(unmapped, key=by_product_key):
            lines.append(bullet(entry))

    lines.append("")
    return "\n".join(lines)


def splice_readme(content, block):
    """Replace the marked listing in README.md, inserting markers if absent.

    Older copies of the README carry only the closing marker, so the opening one
    is placed right after the section heading when it is missing.
    """
    if START_MARKER in content and END_MARKER in content:
        head, _, rest = content.partition(START_MARKER)
        _, _, tail = rest.partition(END_MARKER)
        return f"{head}{block}{tail}"

    heading = "## Vulnerabilities by Product"
    if heading not in content:
        raise SystemExit(f"error: README.md has neither {START_MARKER} nor the '{heading}' heading")

    head, _, rest = content.partition(heading)
    if END_MARKER in rest:
        _, _, tail = rest.partition(END_MARKER)
    else:
        # No markers at all: the listing runs to the next top-level section.
        after = rest.split("\n", 1)[1] if "\n" in rest else ""
        index = after.find("\n## ")
        tail = after[index:] if index != -1 else "\n"
    return f"{head}{heading}\n\n{block}{tail}"


def write(path, content, check):
    """Write a file unless --check, reporting whether it was already current."""
    existing = ""
    if os.path.exists(path):
        with open(path, encoding="utf-8") as handle:
            existing = handle.read()
    name = os.path.relpath(path, REPO_ROOT)
    if existing == content:
        print(f"  = {name} (up to date)")
        return False
    if check:
        print(f"  ! {name} (stale)")
        return True
    with open(path, "w", encoding="utf-8") as handle:
        handle.write(content)
    print(f"  + {name} (rewritten)")
    return True


def main():
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument("--check", action="store_true", help="exit 1 if any index is stale")
    args = parser.parse_args()

    entries = load_entries()
    print(f"{len(entries)} entries\n")

    readme_path = os.path.join(REPO_ROOT, "README.md")
    with open(readme_path, encoding="utf-8") as handle:
        readme = handle.read()

    stale = False
    stale |= write(readme_path, splice_readme(readme, render_product_index(entries)), args.check)
    stale |= write(
        os.path.join(REPO_ROOT, "INDEX_BY_CLASS.md"), render_class_index(entries), args.check
    )
    stale |= write(
        os.path.join(REPO_ROOT, "INDEX_BY_CWE.md"), render_cwe_index(entries), args.check
    )

    if args.check and stale:
        print("\nindices are stale; run: python3 tools/gen_indices.py")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
